# Generated by Django 3.2.15 on 2022-09-30 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=30, unique=True, verbose_name='first name')),
                ('last_name', models.CharField(max_length=30, verbose_name='last name')),
                ('username', models.CharField(blank=True, max_length=60, null=True, verbose_name='username')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='date of birth')),
                ('contacts', models.CharField(blank=True, max_length=255, null=True, verbose_name='contacts')),
                ('biography', models.TextField(blank=True, null=True, verbose_name='biography')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
