# Generated by Django 3.2.15 on 2022-10-01 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='model name')),
                ('model_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='model id')),
                ('action_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
